push message
hemvanh/TPTEA pull request #104
Opened 2018-12-14 13:21 UTC by tri-et

2018-12-17 06:29 UTC, hemvanh requested changes

2018-12-17 06:29 UTC, hemvanh commented on .eslintrc.js
> +    clients: true,
purpose of this ?

2018-12-17 06:29 UTC, hemvanh commented on quasar.conf.js
> +        gcm_sender_id: '889927801023',
where to get this Id, is it hard-coded and work forever ?

2018-12-17 06:29 UTC, hemvanh commented on server/schema/customer/res.js
> +      return await PushSubscription.create(input).then(async () => {
async ()  => {}  --> why need async ????

2018-12-17 06:29 UTC, hemvanh commented on server/schema/admin/res.js
> +      let pushComlepted = Promise.resolve()
pushComlepted ---> what is it for ???
pls find a proper way of using synced promise ....
try: https://caolan.github.io/async/
or proper native Promise implementation

2018-12-17 06:29 UTC, hemvanh commented on src-pwa/custom-service-worker.js
> +  self.registration.getNotifications().then(function(notifications) {
why need to close all notifications ??

2018-12-17 06:29 UTC, hemvanh commented on src-pwa/register-service-worker.js
> +      if (sub === null) {
if(sub) or if(!sub)

2018-12-17 06:29 UTC, hemvanh commented on package-lock.json
> +  "version": "0.0.2",
pls exclude your packpage-lock.json

2018-12-17 06:32 UTC, tri-et commented on quasar.conf.js
> +        gcm_sender_id: '889927801023',
this id we got from https://console.firebase.google.com,
register account and create project

2018-12-17 06:36 UTC, tri-et commented on .eslintrc.js
> +    clients: true,
for eslint  dont show error like workbox

2018-12-17 06:37 UTC, hemvanh commented on quasar.conf.js
> +        gcm_sender_id: '889927801023',
so this using Firebase push ?

2018-12-17 06:49 UTC, tri-et commented on src-pwa/custom-service-worker.js
> +  self.registration.getNotifications().then(function(notifications) {
when we click one of all notification it'll show all notification in list so i close all notifications

2018-12-18 04:36 UTC, hemvanh approved these changes

2018-12-18 04:36 UTC, merged