handle button add to card
hemvanh/TPTEA pull request #112
Opened 2019-01-04 09:09 UTC by tri-et

2019-01-04 09:43 UTC, hemvanh requested changes

2019-01-04 09:43 UTC, hemvanh commented on src/components/ModifiersGroup.vue
> +    ...mapGetters('modifier', ['getCurrentMenuModifier']),
getCurrentMenuModifier -> getCurrentMenuModifiers

2019-01-04 09:43 UTC, hemvanh commented on src/components/ModifiersGroup.vue
> +      handler(newModifiers, oldModifiers) {
handler(newModifiers, oldModifiers) {....  -> handler: this.updateModifiers

pls note: update is 1 word, not upDate

2019-01-04 09:43 UTC, hemvanh commented on src/components/ModifiersGroup.vue
>      if (modifierDedault) this.defaultModifiers = modifierDedault
this.defaultModifiers =_d.find(this.data, modifier => {
             return modifier.isDefault
  })

2019-01-04 09:43 UTC, hemvanh commented on src/pages/MenuDetail.vue
> +    calculatorMenuPrice() {
calculatorMenuPrice -> calculateMenuPrice

2019-01-04 09:43 UTC, hemvanh commented on src/pages/MenuDetail.vue
> +      let menuModifierPrice =
menuModifierPrice  -> menuPrice

2019-01-04 09:43 UTC, hemvanh commented on src/store/customer-order/actions.js
> +/*
remove comments ?

2019-01-04 09:43 UTC, hemvanh commented on src/store/modifier/state.js
> +  currentMenuModifier: [],
currentMenuModifier -> currentMenuModifiers

2019-01-04 09:43 UTC, hemvanh commented on src/components/ModifiersGroup.vue
> +    upDateModifiers(newModifiers, oldModifiers) {
upDateModifiers -> updateModifiers

2019-01-07 07:10 UTC, hemvanh requested changes

2019-01-07 07:10 UTC, hemvanh commented on src/components/ModifiersGroup.vue
> +      handler(newModifiers, oldModifiers) {
havent fixed this

2019-01-07 07:10 UTC, hemvanh commented on src/pages/MenuDetail.vue
> +    addToCard() {
-> addToCart

2019-01-07 09:04 UTC, hemvanh requested changes

2019-01-07 09:04 UTC, hemvanh commented on src/components/ModifiersGroup.vue
> +  this.setCurrentMenuModifier(_d.concat(currentModifiers, newModifiers))
setCurrentMenuModifier -> setCurrentMenuModifiers

2019-01-07 09:04 UTC, hemvanh commented on src/pages/MenuDetail.vue
> +        modifierId: this.modifierId,
modifierIds ??

2019-01-07 09:04 UTC, hemvanh commented on src/pages/MenuDetail.vue
> +    ...mapMutations('customerorder', {setRecsModifier: 'setRecs'}),
...mapMutations('customerorder', {setRecsModifier: 'setRecs'}),

-> ...mapMutations('customerorder', {addMenuToOrder: 'setRecs'}),

2019-01-07 09:18 UTC, tri-et commented on src/pages/MenuDetail.vue
> +        modifierId: this.modifierId,
u mean modifierId->modifierIds or what's purpose using 'modifierId'?

2019-01-07 10:39 UTC, hemvanh requested changes

2019-01-07 10:39 UTC, hemvanh commented on src/components/ModifiersGroup.vue
> +      oldModifiers: [],
oldModifiers --> no use right ?

2019-01-07 10:44 UTC, merged