login facebook
hemvanh/TPTEA pull request #17
Opened 2018-10-03 03:01 UTC by tri-et

2018-10-03 04:12 UTC, hemvanh requested changes
please fix all the issues as commented

2018-10-03 04:12 UTC, hemvanh commented on server/schema/customer/def.js
> +  type RegFbRes {
RegFbRes  -> RegisterFbResponse

2018-10-03 04:12 UTC, hemvanh commented on server/schema/customer/def.js
>    input RegInput {
RegInput -> RegisterInput

2018-10-03 04:12 UTC, hemvanh commented on server/schema/customer/res.js
>      async reg(_, {input}) {
reg -> register

2018-10-03 04:12 UTC, hemvanh commented on server/schema/customer/res.js
> +    async loginFB(_, {input}) {
loginFB -> loginFb

2018-10-03 04:12 UTC, hemvanh commented on server/schema/customer/res.js
> +    async regFB(_, {input}) {
regFB -> registerFb

2018-10-03 04:12 UTC, hemvanh commented on server/schema/customer/res.js
> +      input.password = bcrypt.hashSync(input.password, SALT)
why need password ?

2018-10-03 04:12 UTC, hemvanh commented on server/schema/customer/res.js
> +        user = await Customer.findOne({where: {username: input.username}})
user already available above, why need to findOne again?

2018-10-03 04:12 UTC, hemvanh commented on server/schema/index.js
> +    regFB(input:RegInput): RegFbRes
regFB(input:RegInput): RegFbRes
-> registerFb(input:RegisterInput): RegisterFbResponse
*note: aslways use "Fb"  dont mix with "FB"

2018-10-03 04:12 UTC, hemvanh commented on src/index.template.html
> +  <script src="statics/fb.js"></script>
fb.js -> fb-api-v1.2.3.js

2018-10-03 04:12 UTC, hemvanh commented on src/pages/Login.vue
> +    loginFB() {
1)why need to seperate into 2 functions: loginCustumerFB() , loginFB()
can put "window.FB.login(res => { ... into vuex action loginFB ?
2)same as above for Register
3)wrong Custumer -> Customer , FB -> Fb

2018-10-03 04:12 UTC, hemvanh commented on src/store/customer/actions.js
> +export function loginCustumerFB({commit}, payload) {
why use loginCustumerFB, can just use loginFb(), which call to the mutation loginFb

2018-10-03 04:12 UTC, hemvanh commented on src/store/customer/actions.js
> +export function regCustomerFB({commit}, payload) {
regCustomerFB -> registerFb

2018-10-03 04:12 UTC, hemvanh commented on src/store/customer/actions.js
> +      regFB(input: $input) {
regFB -> registerFb

2018-10-03 08:12 UTC, tri-et commented on server/schema/customer/res.js
> +        user = await Customer.findOne({where: {username: input.username}})
because we need user's id just registered for set token

2018-10-03 09:16 UTC, hemvanh requested changes
refactor jwt part to generateLoginJwt()
be careful when use upsert

2018-10-03 09:16 UTC, hemvanh commented on server/schema/customer/res.js
> +      return await Customer.upsert(input).then(async function() {
upsert -> insert to be safe, coz update should not be happening here

2018-10-03 09:16 UTC, hemvanh commented on server/schema/customer/res.js
> +      const user = await Customer.findOne({where: {username: input.username}})
refactor this part into a reusable async function
ex:      async generateLoginJwt(username)  -> return jwt.sign(....)

2018-10-03 11:15 UTC, hemvanh requested changes
refactor 1 more time

2018-10-03 11:15 UTC, hemvanh commented on server/schema/customer/mutations.js
> +import jwt from 'jsonwebtoken'
why need to put in mutations.js ?

2018-10-03 11:15 UTC, hemvanh commented on server/schema/customer/res.js
> +      return generateLoginJwt(Customer, input)
un-necessary passing of Customer

2018-10-04 04:39 UTC, hemvanh requested changes
simplify the params passing for generateLoginJwt()

2018-10-04 04:39 UTC, hemvanh commented on server/schema/customer/res.js
> +async function generateLoginJwt(input, msg = '') {
input -> customer , best send in "username" only
** and why do we need to pass-in object, while we only need username for searching ?
for the naming scheme "input" is just too unambiguous!

2018-10-04 05:08 UTC, hemvanh approved these changes

2018-10-04 08:27 UTC, merged