server _auth and _authAdmin validation
hemvanh/TPTEA pull request #26
Opened 2018-10-12 06:58 UTC by tri-et

2018-10-12 09:35 UTC, hemvanh requested changes

2018-10-12 09:35 UTC, hemvanh commented on server/util.js
> +    throw new Error('Please login first!')
Please login as an Admin first!

2018-10-12 09:35 UTC, hemvanh commented on server/util.js
> +    throw new Error('Account not admin!')
This Account is not an Admin!

2018-10-12 09:35 UTC, hemvanh commented on server/util.js
> +    throw new Error('Account not customer!')
This is not a Valid Customer account!

2018-10-12 09:35 UTC, hemvanh commented on src/store/customer/actions.js
> +      if (data.errors) _alert(data.errors[0].message, 'warning')
should the error already been taken care in: .catch(err => { ... ?

2018-10-13 06:21 UTC, tri-et commented on src/store/customer/actions.js
> +      if (data.errors) _alert(data.errors[0].message, 'warning')
catch just show error api graphql don't show error customize

2018-10-13 07:07 UTC, hemvanh approved these changes

2018-10-13 07:07 UTC, merged