Admin login field Validator
hemvanh/TPTEA pull request #30
Opened 2018-10-16 09:58 UTC by Se7en-et

2018-10-17 09:21 UTC, hemvanh requested changes

2018-10-17 09:21 UTC, hemvanh commented on src/pages/admin/Login.vue
> +      <div class="row justify-center" style="height:60px;width:100%;">
pls create a stylus class for this :  height:60px;width:100%;

2018-10-18 07:42 UTC, phong-et commented
I changed

2018-10-19 03:43 UTC, hemvanh requested changes
pls help update changelog also

2018-10-19 05:13 UTC, hemvanh requested changes

2018-10-19 05:13 UTC, hemvanh commented on CHANGELOG.md
> +- Admin validator
Admin validator  -> Admin Login validator

2018-10-19 05:14 UTC, Se7en-et commented on CHANGELOG.md
> +- Admin validator
ok a

2018-10-19 07:01 UTC, merged